name: Docker build and upload to GitHub

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docker/**'
      - '.github/workflows/docker.yml'
      - '!docker/README.md'
      - '!docker/docker-README.md'
      - '!docker/Dockerfile.sshd'
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'docker/**'
      - '!docker/README.md'
      - '!docker/docker-README.md'
      - '!docker/Dockerfile.sshd'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Git Checkout
        uses: actions/checkout@v3
      - 
        name: Lint Dockerfile
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: 'docker/Dockerfile'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:v0.11.1
          buildkitd-flags: --debug
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: "{{defaultContext}}:docker"
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/namratajha/kali:latest
